Gen ← ×⊃(;:;:;:)(+⊃(⌕;:)(⌕;);)-@0.

Oq ← Gen @1 "one"
Ow ← Gen @2 "two"
Oe ← Gen @3 "three"
Or ← Gen @4 "four"
Ot ← Gen @5 "five"
Oz ← Gen @6 "six"
Ou ← Gen @7 "seve"
Oi ← Gen @8 "eight"
Oo ← Gen @9 "nine"

f ← +⊃(+⊃(+⊃(+⊃Oq Ow) Oe)(+⊃Or Ot))(+⊃(+⊃Oz Ou)(+⊃Oi Oo))
g ← /+×10_1⊏⊃(⊟⊃(⊗0)(-1-⊃(⊗0⇌)(⧻))=0)∘

/+[g f "two1nine"
   g f "eightwothree"
   g f "abcone2threexyz"
   g f "xtwone3four"
   g f "4nineeightseven2"
   g f "zoneight234"
   g f "7pqrstsixteen"]